version: '3.8'
services:
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        image: blog
        container_name: blog-dev
        ports:
            - '3131:3131'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            NODE_ENV: development
        command: npm run dev
